### ISSUE TITLE
doesn't copy Fedora

### ISSUE THREAD

**Issue by Rignchen** [bth123/mcf-ansi-highlighter#1]
I'm on my laptop (HP BANG % OLUFSEN) with Linux Fedora 38 as OS and when I press the Copy Highlighted button it shows a popup saying "text copied" but when I try to past it inside discord it past what I copied before going on the website, I tried to manually copy from the popup but I can't select the text

**Comment by bth123** [comment]
Have you allowed using your clipboard in browser settings? Also try to click Ok on popup, maybe browser will ask to use your clipboard as in Edge (idk, never used linux ngl)

**Comment by Rignchen** [comment]
I tried pressing ok but nothing happend and I can copy text from internet if I select it and press ctrl + C
